import { type CountryCode } from "./countryToContinent";

export const cityToCountryMap = {
  // North America
  "New York": "US",
  Boston: "US",
  Chicago: "US",
  "San Francisco": "US",
  "Los Angeles": "US",
  Seattle: "US",
  Miami: "US",
  Houston: "US",
  Atlanta: "US",
  Denver: "US",
  Portland: "US",
  Austin: "US",
  Dallas: "US",
  Philadelphia: "US",
  Phoenix: "US",
  Toronto: "CA",
  Vancouver: "CA",
  Montreal: "CA",
  Montréal: "CA",
  Ottawa: "CA",
  Calgary: "CA",
  Edmonton: "CA",
  "Quebec City": "CA",
  "Mexico City": "MX",
  Guadalajara: "MX",
  Cancún: "MX",

  // Europe
  London: "GB",
  Manchester: "GB",
  Birmingham: "GB",
  Edinburgh: "GB",
  Glasgow: "GB",
  Leeds: "GB",
  Bristol: "GB",
  Liverpool: "GB",
  Paris: "FR",
  Lyon: "FR",
  Toulouse: "FR",
  Bordeaux: "FR",
  Lille: "FR",
  Berlin: "DE",
  Hamburg: "DE",
  Munich: "DE",
  München: "DE",
  Frankfurt: "DE",
  Köln: "DE",
  Stuttgart: "DE",
  Düsseldorf: "DE",
  Dresden: "DE",
  Leipzig: "DE",
  Amsterdam: "NL",
  Rotterdam: "NL",
  "The Hague": "NL",
  Utrecht: "NL",
  Madrid: "ES",
  Barcelona: "ES",
  Valencia: "ES",
  Seville: "ES",
  Bilbao: "ES",
  Rome: "IT",
  Roma: "IT",
  Milan: "IT",
  Milano: "IT",
  Turin: "IT",
  Torino: "IT",
  Florence: "IT",
  Stockholm: "SE",
  Gothenburg: "SE",
  Malmö: "SE",
  Uppsala: "SE",
  Oslo: "NO",
  Bergen: "NO",
  Trondheim: "NO",
  Copenhagen: "DK",
  København: "DK",
  Aarhus: "DK",
  Helsinki: "FI",
  Espoo: "FI",
  Tampere: "FI",
  Turku: "FI",
  Dublin: "IE",
  Cork: "IE",
  Galway: "IE",
  Brussels: "BE",
  Bruxelles: "BE",
  Antwerp: "BE",
  Ghent: "BE",
  Gent: "BE",
  Vienna: "AT",
  Wien: "AT",
  Graz: "AT",
  Linz: "AT",
  Zürich: "CH",
  Geneva: "CH",
  Genève: "CH",
  Basel: "CH",
  Bern: "CH",
  Warsaw: "PL",
  Warszawa: "PL",
  Kraków: "PL",
  Wrocław: "PL",
  Prague: "CZ",
  Praha: "CZ",
  Brno: "CZ",
  Budapest: "HU",
  Bucharest: "RO",
  București: "RO",
  Sofia: "BG",
  Athens: "GR",
  Lisbon: "PT",
  Lisboa: "PT",
  Porto: "PT",
  Москва: "RU", // Moscow
  "Санкт-Петербург": "RU", // Saint Petersburg
  Київ: "UA", // Kyiv

  // Asia
  Tokyo: "JP",
  Singapore: "SG",
  "Hong Kong": "HK",
  Seoul: "KR",
  Beijing: "CN",
  Shanghai: "CN",
  Shenzhen: "CN",
  Mumbai: "IN",
  Bengaluru: "IN",
  Delhi: "IN",
  Bangkok: "TH",
  Dubai: "AE",
  "Abu Dhabi": "AE",

  // Oceania
  Sydney: "AU",
  Melbourne: "AU",
  Brisbane: "AU",
  Perth: "AU",
  Auckland: "NZ",

  // South America
  "São Paulo": "BR",
  "Rio de Janeiro": "BR",
  "Buenos Aires": "AR",
  Santiago: "CL",
  Lima: "PE",
  Bogotá: "CO",
  Montevideo: "UY",
  Caracas: "VE",

  // Africa
  "Cape Town": "ZA",
  Johannesburg: "ZA",
  Nairobi: "KE",
  Cairo: "EG",
  Lagos: "NG",
} as const;

export function getCountryForCity(city: string): CountryCode {
  return cityToCountryMap[city as keyof typeof cityToCountryMap] || "Unknown";
}
