export const regionToCountryMap = {
  // United States regions
  FL: "US",
  CA: "US",
  SC: "US",
  MO: "US",
  IL: "US",
  OH: "US",
  NY: "US",
  IA: "US",
  CO: "US",
  VA: "US",
  MI: "US",
  NJ: "US",
  GA: "US",
  AR: "US",
  NM: "US",
  NC: "US",
  MA: "US",
  CT: "US",
  TN: "US",
  KY: "US",
  IN: "US",
  HI: "US",
  MN: "US",
  MD: "US",
  WA: "US",
  VT: "US",
  MS: "US",
  UT: "US",
  NB: "US",
  OK: "US",
  PA: "US",
  OR: "US",
  LA: "US",
  KS: "US",
  MT: "US",
  ID: "US",
  AL: "US",
  NE: "US",
  AK: "US",
  NV: "US",
  DC: "US",
  WI: "US",
  SK: "US",

  // German regions
  "Baden-Württemberg": "DE",
  "Nordrhein-Westfalen": "DE",
  Bayern: "DE",
  Thüringen: "DE",
  Brandenburg: "DE",
  Niedersachsen: "DE",
  Hamburg: "DE",
  Hessen: "DE",
  Sachsen: "DE",
  "Rheinland-Pfalz": "DE",
  "Sachsen-Anhalt": "DE",
  Berlin: "DE",

  // UK regions
  England: "GB",
  Scotland: "GB",
  Wales: "GB",
  "Northern Ireland": "GB",

  // Canadian regions
  Ontario: "CA",
  Quebec: "CA",
  Québec: "CA",
  "British Columbia": "CA",
  Alberta: "CA",
  Manitoba: "CA",
  QC: "CA",
  ON: "CA",
  BC: "CA",
  AB: "CA",

  // Australian regions
  "New South Wales": "AU",
  Victoria: "AU",
  Queensland: "AU",
  "Western Australia": "AU",
  "South Australia": "AU",
  NSW: "AU",
  VIC: "AU",
  QLD: "AU",
  SA: "AU",

  // Spanish regions
  Andalusia: "ES",
  Andalucía: "ES",
  Cataluña: "ES",
  Catalunya: "ES",
  Madrid: "ES",
  "Comunidad de Madrid": "ES",
  "País Vasco": "ES",
  "Balearic Isles": "ES",
  "Balearische Inseln": "ES",
  Cádiz: "ES",
  Málaga: "ES",
  Aragón: "ES",
  Canarias: "ES",
  Álava: "ES",
  "Principado de Asturias": "ES",

  // French regions
  "Île-de-France": "FR",
  "Auvergne-Rhône-Alpes": "FR",
  "Hauts-de-France": "FR",
  Bretagne: "FR",
  Corse: "FR",

  // Italian regions
  Lombardia: "IT",
  Lombardy: "IT",
  Lazio: "IT",
  "Emilia-Romagna": "IT",
  Piemonte: "IT",
  Campania: "IT",
  Puglia: "IT",
  Sicilia: "IT",
  Südtirol: "IT",
  "Friuli-Venezia Giulia": "IT",

  // Other European regions
  Lisboa: "PT",
  Lisbon: "PT",
  Faro: "PT",
  "Noord-Holland": "NL",
  "Zuid-Holland": "NL",
  "South Holland": "NL",
  "Noord-Brabant": "NL",
  Utrecht: "NL",
  Gelderland: "NL",
  Friesland: "NL",
  Drenthe: "NL",
  Groningen: "NL",
  Flanders: "BE",
  "Vlaams Gewest": "BE",
  "Brabant wallon": "BE",
  "West Flanders": "BE",
  "Oost-Vlaanderen": "BE",
  Antwerpen: "BE",
  Hovedstaden: "DK",
  "Region Hovedstaden": "DK",
  Midtjylland: "DK",
  Uusimaa: "FI",
  "Etelä-Karjala": "FI",
  "Keski-Suomi": "FI",
  "Etelä-Savo": "FI",
  "Keski-Pohjanmaa": "FI",
  "Västra Götaland": "SE",
  "Västra Götalands län": "SE",
  Stockholm: "SE",
  Skåne: "SE",
  "Hallands län": "SE",
  "Västernorrlands län": "SE",
  "Västerbottens län": "SE",
  Norrbotten: "SE",
  "Värmlands län": "SE",
  Oslo: "NO",
  Rogaland: "NO",
  Wien: "AT",
  Tirol: "AT",
  Oberösterreich: "AT",
  "Upper Austria": "AT",
  Niederösterreich: "AT",
  Kärnten: "AT",
  Steiermark: "AT",
  Salzburg: "AT",
  Aargau: "CH",
  "Sankt Gallen": "CH",
  Zürich: "CH",
  "Canton of Bern": "CH",
  "Kanton Zürich": "CH",

  // Brazilian regions
  "São Paulo": "BR",
  "State of São Paulo": "BR",
  "Minas Gerais": "BR",
  Paraná: "BR",
  "Rio de Janeiro": "BR",
  "Rio Grande do Sul": "BR",
  "Mato Grosso do Sul": "BR",
  "Rio Grande do Norte": "BR",
  "Espírito Santo": "BR",
  SP: "BR",
  RJ: "BR",

  // Asian regions
  "Metro Manila": "PH",
  Tokyo: "JP",
  Niigata: "JP",
  "North Gyeongsang": "KR",
  Haryana: "IN",
  Karnataka: "IN",
  Maharashtra: "IN",
  Bali: "ID",
  Terengganu: "MY",
  四川省: "CN",
  广东省: "CN",

  // Other regions
  Gauteng: "ZA",
  "Western Cape": "ZA",
  "Región Metropolitana": "CL",
  "La Araucanía": "CL",
  CDMX: "MX",
  Jalisco: "MX",
  "Buenos Aires": "AR",
  "Buenos Aires Province": "AR",
  "Provincia de Buenos Aires": "AR",
  CABA: "AR",
  "Departamento de Montevideo": "UY",
  Quindío: "CO",
  "Distrito Capital": "VE",
  "County Dublin": "IE",
  "Co. Dublin": "IE",
  "County Kildare": "IE",
  "Co. Wexford": "IE",
  "Rabat-Salé-Zemmour-Zaer": "MA",
  "Актюбинская область": "KZ",
  Київ: "UA",
  Москва: "RU",
  "Moscow Oblast": "RU",
  Dolnośląskie: "PL",
  Wielkopolskie: "PL",
  Małopolskie: "PL",
  Mazowieckie: "PL",
  "Western Pomerania": "PL",
  Podlaskie: "PL",
  "Județul Bihor": "RO",
  "Județul Argeș": "RO",
  Sibiu: "RO",
  "Jihomoravský kraj": "CZ",
  "Hlavní město Praha": "CZ",
  "Středočeský kraj": "CZ",
  "Plzeňský kraj": "CZ",
  Olomouc: "CZ",
  "City of Zagreb": "HR",
  "Zagreb County": "HR",
} as const;
