// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;

  /**
   * Profile Image field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.profile_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_image: prismic.ImageField<never>;

  /**
   * Description field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * instagramUrl field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.instagramurl
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagramurl: prismic.KeyTextField;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

type BlogPostDocumentDataSlicesSlice =
  | FaqsSlice
  | TableSlice
  | CalloutSlice
  | CtaInfoSlice
  | TldrBoxSlice
  | RichTextSlice;

/**
 * Content for Blog post documents
 */
interface BlogPostDocumentData {
  /**
   * Read time field in *Blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.read_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  read_time: prismic.KeyTextField;

  /**
   * Title field in *Blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Author field in *Blog post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField;

  /**
   * Slice Zone field in *Blog post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Item in *LP Dating Photographer → Table*
 */
export interface BlogwithphotosDocumentDataTableItem {
  /**
   * Col1 field in *LP Dating Photographer → Table*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogwithphotos.table[].col1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  col1: prismic.KeyTextField;

  /**
   * Col2 field in *LP Dating Photographer → Table*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogwithphotos.table[].col2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  col2: prismic.KeyTextField;
}

type BlogwithphotosDocumentDataSlicesSlice =
  | HeroSectionSlice
  | SectionRichTextImageSlice
  | RichTextSlice
  | TripplePhotoSlice
  | SectionWithHeadingSlice
  | H1WithSubHeadingSlice;

/**
 * Content for LP Dating Photographer documents
 */
interface BlogwithphotosDocumentData {
  /**
   * PageTitle field in *LP Dating Photographer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogwithphotos.pagetitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pagetitle: prismic.KeyTextField;

  /**
   * CoverPhoto field in *LP Dating Photographer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogwithphotos.coverPhoto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  coverPhoto: prismic.ImageField<never>;

  /**
   * Table field in *LP Dating Photographer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blogwithphotos.table[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  table: prismic.GroupField<Simplify<BlogwithphotosDocumentDataTableItem>>;

  /**
   * Slice Zone field in *LP Dating Photographer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogwithphotos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogwithphotosDocumentDataSlicesSlice> /**
   * Meta Title field in *LP Dating Photographer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogwithphotos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *LP Dating Photographer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogwithphotos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *LP Dating Photographer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogwithphotos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * LP Dating Photographer document from Prismic
 *
 * - **API ID**: `blogwithphotos`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogwithphotosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogwithphotosDocumentData>,
    "blogwithphotos",
    Lang
  >;

type PawBlogDocumentDataSlicesSlice =
  | SectionWithHeadingSlice
  | RichTextSlice
  | CalloutSlice
  | YouMayAlsoLikeSlice
  | AuthorBoxSlice
  | TldrBoxSlice
  | H1WithSubHeadingSlice;

/**
 * Content for Paw blog documents
 */
interface PawBlogDocumentData {
  /**
   * Slice Zone field in *Paw blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: paw_blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PawBlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Paw blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: paw_blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Paw blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: paw_blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Paw blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: paw_blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Paw blog document from Prismic
 *
 * - **API ID**: `paw_blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PawBlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PawBlogDocumentData>,
    "paw_blog",
    Lang
  >;

type PawBlogTestDocumentDataSlicesSlice =
  | TestimonialSlice
  | RichTextSlice
  | SectionWithHeadingSlice
  | CtaInfoSlice
  | H1WithSubHeadingSlice
  | CalloutSlice
  | AuthorBoxSlice;

/**
 * Content for Paw Blog Test documents
 */
interface PawBlogTestDocumentData {
  /**
   * Slice Zone field in *Paw Blog Test*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: paw_blog_test.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PawBlogTestDocumentDataSlicesSlice> /**
   * Meta Title field in *Paw Blog Test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: paw_blog_test.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Paw Blog Test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: paw_blog_test.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Paw Blog Test*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: paw_blog_test.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Paw Blog Test document from Prismic
 *
 * - **API ID**: `paw_blog_test`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PawBlogTestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PawBlogTestDocumentData>,
    "paw_blog_test",
    Lang
  >;

export type AllDocumentTypes =
  | AuthorDocument
  | BlogPostDocument
  | BlogwithphotosDocument
  | PawBlogDocument
  | PawBlogTestDocument;

/**
 * Primary content in *AuthorBox → Default → Primary*
 */
export interface AuthorBoxSliceDefaultPrimary {
  /**
   * Author Image field in *AuthorBox → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author_box.default.primary.author_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_image: prismic.ImageField<never>;

  /**
   * Author Name field in *AuthorBox → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author_box.default.primary.author_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Role field in *AuthorBox → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author_box.default.primary.author_role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_role: prismic.KeyTextField;

  /**
   * Author description field in *AuthorBox → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author_box.default.primary.author_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_description: prismic.KeyTextField;

  /**
   * Author Instagram field in *AuthorBox → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author_box.default.primary.author_instagram
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author_instagram: prismic.LinkField;

  /**
   * Author LinkedIn field in *AuthorBox → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author_box.default.primary.author_linkedin
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author_linkedin: prismic.LinkField;

  /**
   * Author X field in *AuthorBox → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author_box.default.primary.author_x
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author_x: prismic.LinkField;
}

/**
 * Default variation for AuthorBox Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AuthorBoxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AuthorBoxSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AuthorBox*
 */
type AuthorBoxSliceVariation = AuthorBoxSliceDefault;

/**
 * AuthorBox Shared Slice
 *
 * - **API ID**: `author_box`
 * - **Description**: AuthorBox
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AuthorBoxSlice = prismic.SharedSlice<
  "author_box",
  AuthorBoxSliceVariation
>;

/**
 * Item in *Bullets → Default → Primary → Bullets*
 */
export interface BulletsSliceDefaultPrimaryBulletsItem {
  /**
   * Bold field in *Bullets → Default → Primary → Bullets*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bullets.default.primary.bullets[].bold
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bold: prismic.KeyTextField;

  /**
   * Body field in *Bullets → Default → Primary → Bullets*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bullets.default.primary.bullets[].body
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;
}

/**
 * Primary content in *Bullets → Default → Primary*
 */
export interface BulletsSliceDefaultPrimary {
  /**
   * Bullets field in *Bullets → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bullets.default.primary.bullets[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  bullets: prismic.GroupField<Simplify<BulletsSliceDefaultPrimaryBulletsItem>>;

  /**
   * Emoji field in *Bullets → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bullets.default.primary.emoji
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  emoji: prismic.KeyTextField;
}

/**
 * Default variation for Bullets Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BulletsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BulletsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Bullets*
 */
type BulletsSliceVariation = BulletsSliceDefault;

/**
 * Bullets Shared Slice
 *
 * - **API ID**: `bullets`
 * - **Description**: Bullets
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BulletsSlice = prismic.SharedSlice<
  "bullets",
  BulletsSliceVariation
>;

/**
 * Primary content in *Callout → Default → Primary*
 */
export interface CalloutSliceDefaultPrimary {
  /**
   * Emoji field in *Callout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.default.primary.emoji
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  emoji: prismic.KeyTextField;

  /**
   * RichTest field in *Callout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.default.primary.richtest
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  richtest: prismic.RichTextField;

  /**
   * Bold field in *Callout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.default.primary.bold
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bold: prismic.KeyTextField;

  /**
   * Rest field in *Callout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.default.primary.rest
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  rest: prismic.KeyTextField;
}

/**
 * Default variation for Callout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CalloutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Callout*
 */
type CalloutSliceVariation = CalloutSliceDefault;

/**
 * Callout Shared Slice
 *
 * - **API ID**: `callout`
 * - **Description**: Callout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutSlice = prismic.SharedSlice<
  "callout",
  CalloutSliceVariation
>;

/**
 * Item in *ContentCentered → Default → Primary → Bullets*
 */
export interface ContentCenteredSliceDefaultPrimaryBulletsItem {
  /**
   * Bold field in *ContentCentered → Default → Primary → Bullets*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_centered.default.primary.bullets[].bold
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bold: prismic.KeyTextField;

  /**
   * Content field in *ContentCentered → Default → Primary → Bullets*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_centered.default.primary.bullets[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *ContentCentered → Default → Primary*
 */
export interface ContentCenteredSliceDefaultPrimary {
  /**
   * Eyebrow field in *ContentCentered → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_centered.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *ContentCentered → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_centered.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Intro field in *ContentCentered → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_centered.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro: prismic.KeyTextField;

  /**
   * Paragraph1 field in *ContentCentered → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_centered.default.primary.paragraph1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph1: prismic.RichTextField;

  /**
   * Bullets field in *ContentCentered → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_centered.default.primary.bullets[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  bullets: prismic.GroupField<
    Simplify<ContentCenteredSliceDefaultPrimaryBulletsItem>
  >;

  /**
   * Paragraph2 field in *ContentCentered → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_centered.default.primary.paragraph2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph2: prismic.RichTextField;
}

/**
 * Default variation for ContentCentered Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentCenteredSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentCenteredSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentCentered*
 */
type ContentCenteredSliceVariation = ContentCenteredSliceDefault;

/**
 * ContentCentered Shared Slice
 *
 * - **API ID**: `content_centered`
 * - **Description**: ContentCentered
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentCenteredSlice = prismic.SharedSlice<
  "content_centered",
  ContentCenteredSliceVariation
>;

/**
 * Primary content in *ContentWithTestimonialsAndStats → Default → Primary*
 */
export interface ContentWithTestimonialsAndStatsSliceDefaultPrimary {
  /**
   * Testimonial Background Image field in *ContentWithTestimonialsAndStats → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_testimonials_and_stats.default.primary.testimonial_background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  testimonial_background_image: prismic.ImageField<never>;

  /**
   * Testimonial Company field in *ContentWithTestimonialsAndStats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_testimonials_and_stats.default.primary.testimonial_company
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial_company: prismic.KeyTextField;

  /**
   * Testimonial quote field in *ContentWithTestimonialsAndStats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_testimonials_and_stats.default.primary.testimonial_quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial_quote: prismic.KeyTextField;

  /**
   * Testimonial name field in *ContentWithTestimonialsAndStats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_testimonials_and_stats.default.primary.testimonial_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial_name: prismic.KeyTextField;

  /**
   * Testimonial title field in *ContentWithTestimonialsAndStats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_testimonials_and_stats.default.primary.testimonial_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial_title: prismic.KeyTextField;

  /**
   * Content Eyebrow field in *ContentWithTestimonialsAndStats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_testimonials_and_stats.default.primary.content_eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content_eyebrow: prismic.KeyTextField;

  /**
   * Content Title field in *ContentWithTestimonialsAndStats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_testimonials_and_stats.default.primary.content_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content_title: prismic.KeyTextField;
}

/**
 * Default variation for ContentWithTestimonialsAndStats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWithTestimonialsAndStatsSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<ContentWithTestimonialsAndStatsSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *ContentWithTestimonialsAndStats*
 */
type ContentWithTestimonialsAndStatsSliceVariation =
  ContentWithTestimonialsAndStatsSliceDefault;

/**
 * ContentWithTestimonialsAndStats Shared Slice
 *
 * - **API ID**: `content_with_testimonials_and_stats`
 * - **Description**: ContentWithTestimonialsAndStats
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWithTestimonialsAndStatsSlice = prismic.SharedSlice<
  "content_with_testimonials_and_stats",
  ContentWithTestimonialsAndStatsSliceVariation
>;

/**
 * Primary content in *CtaInfo → Default → Primary*
 */
export interface CtaInfoSliceDefaultPrimary {
  /**
   * Emoji field in *CtaInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_info.default.primary.emoji
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  emoji: prismic.KeyTextField;

  /**
   * Heading field in *CtaInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_info.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *CtaInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_info.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;

  /**
   * Link field in *CtaInfo → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_info.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for CtaInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaInfo*
 */
type CtaInfoSliceVariation = CtaInfoSliceDefault;

/**
 * CtaInfo Shared Slice
 *
 * - **API ID**: `cta_info`
 * - **Description**: CtaInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaInfoSlice = prismic.SharedSlice<
  "cta_info",
  CtaInfoSliceVariation
>;

/**
 * Item in *Faq → Default → Primary → Questions And Answers*
 */
export interface FaqsSliceDefaultPrimaryQuestionsAndAnswersItem {
  /**
   * Question field in *Faq → Default → Primary → Questions And Answers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.questions_and_answers[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Faq → Default → Primary → Questions And Answers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.questions_and_answers[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * Questions And Answers field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.questions_and_answers[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  questions_and_answers: prismic.GroupField<
    Simplify<FaqsSliceDefaultPrimaryQuestionsAndAnswersItem>
  >;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqsSliceVariation = FaqsSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Primary content in *HeadingWithSubHeading → H1WithSubheading → Primary*
 */
export interface H1WithSubHeadingSliceDefaultPrimary {
  /**
   * Title field in *HeadingWithSubHeading → H1WithSubheading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: h1_with_sub_heading.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subheading field in *HeadingWithSubHeading → H1WithSubheading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: h1_with_sub_heading.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;
}

/**
 * H1WithSubheading variation for HeadingWithSubHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type H1WithSubHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<H1WithSubHeadingSliceDefaultPrimary>,
  never
>;

/**
 * H2WithSubheading variation for HeadingWithSubHeading Slice
 *
 * - **API ID**: `h2WithSubheading`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type H1WithSubHeadingSliceH2WithSubheading =
  prismic.SharedSliceVariation<
    "h2WithSubheading",
    Record<string, never>,
    never
  >;

/**
 * Slice variation for *HeadingWithSubHeading*
 */
type H1WithSubHeadingSliceVariation =
  | H1WithSubHeadingSliceDefault
  | H1WithSubHeadingSliceH2WithSubheading;

/**
 * HeadingWithSubHeading Shared Slice
 *
 * - **API ID**: `h1_with_sub_heading`
 * - **Description**: H1WithSubHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type H1WithSubHeadingSlice = prismic.SharedSlice<
  "h1_with_sub_heading",
  H1WithSubHeadingSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * PrimaryCtaButtonText field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.primaryctabuttontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primaryctabuttontext: prismic.KeyTextField;

  /**
   * PrimaryCtaButtonHref field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.primaryctabuttonhref
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primaryctabuttonhref: prismic.LinkField;

  /**
   * CtaLinkText field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.ctalinktext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ctalinktext: prismic.KeyTextField;

  /**
   * CtaLinkHref field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.ctalinkHref
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ctalinkHref: prismic.LinkField;

  /**
   * Image1 field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * Image2 field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * Image3 field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image3: prismic.ImageField<never>;

  /**
   * Image4 field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image4: prismic.ImageField<never>;

  /**
   * Image5 field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image5: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Rich Text Block field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.rich_text_block
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text_block: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SectionRichTextImage → Default → Primary*
 */
export interface SectionRichTextImageSliceDefaultPrimary {
  /**
   * sectionTitle field in *SectionRichTextImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_rich_text_image.default.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;

  /**
   * body field in *SectionRichTextImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_rich_text_image.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Right Image field in *SectionRichTextImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_rich_text_image.default.primary.right_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  right_image: prismic.ImageField<never>;
}

/**
 * Default variation for SectionRichTextImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionRichTextImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionRichTextImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionRichTextImage*
 */
type SectionRichTextImageSliceVariation = SectionRichTextImageSliceDefault;

/**
 * SectionRichTextImage Shared Slice
 *
 * - **API ID**: `section_rich_text_image`
 * - **Description**: SectionRichTextImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionRichTextImageSlice = prismic.SharedSlice<
  "section_rich_text_image",
  SectionRichTextImageSliceVariation
>;

/**
 * Primary content in *SectionWithHeading → Default → Primary*
 */
export interface SectionWithHeadingSliceDefaultPrimary {
  /**
   * Title field in *SectionWithHeading → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_with_heading.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *SectionWithHeading → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_with_heading.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for SectionWithHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionWithHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionWithHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionWithHeading*
 */
type SectionWithHeadingSliceVariation = SectionWithHeadingSliceDefault;

/**
 * SectionWithHeading Shared Slice
 *
 * - **API ID**: `section_with_heading`
 * - **Description**: SectionWithHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionWithHeadingSlice = prismic.SharedSlice<
  "section_with_heading",
  SectionWithHeadingSliceVariation
>;

/**
 * Item in *Table → Default → Primary → Rows*
 */
export interface TableSliceDefaultPrimaryRowsItem {
  /**
   * Col1 field in *Table → Default → Primary → Rows*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: table.default.primary.rows[].col1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  col1: prismic.KeyTextField;

  /**
   * Col2 field in *Table → Default → Primary → Rows*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: table.default.primary.rows[].col2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  col2: prismic.KeyTextField;
}

/**
 * Primary content in *Table → Default → Primary*
 */
export interface TableSliceDefaultPrimary {
  /**
   * Rows field in *Table → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: table.default.primary.rows[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rows: prismic.GroupField<Simplify<TableSliceDefaultPrimaryRowsItem>>;
}

/**
 * Default variation for Table Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TableSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Table*
 */
type TableSliceVariation = TableSliceDefault;

/**
 * Table Shared Slice
 *
 * - **API ID**: `table`
 * - **Description**: Table
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableSlice = prismic.SharedSlice<"table", TableSliceVariation>;

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Quote field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote: prismic.KeyTextField;

  /**
   * Author image field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.author_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_image: prismic.ImageField<never>;

  /**
   * Author name field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.author_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author title field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.author_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_title: prismic.KeyTextField;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Testimonial
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

/**
 * Primary content in *TldrBox → Default → Primary*
 */
export interface TldrBoxSliceDefaultPrimary {
  /**
   * Emoji field in *TldrBox → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tldr_box.default.primary.emoji
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  emoji: prismic.KeyTextField;

  /**
   * Tldr Content field in *TldrBox → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tldr_box.default.primary.tldr_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tldr_content: prismic.RichTextField;
}

/**
 * Default variation for TldrBox Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TldrBoxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TldrBoxSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TldrBox*
 */
type TldrBoxSliceVariation = TldrBoxSliceDefault;

/**
 * TldrBox Shared Slice
 *
 * - **API ID**: `tldr_box`
 * - **Description**: TldrBox
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TldrBoxSlice = prismic.SharedSlice<
  "tldr_box",
  TldrBoxSliceVariation
>;

/**
 * Primary content in *TripplePhoto → Default → Primary*
 */
export interface TripplePhotoSliceDefaultPrimary {
  /**
   * Title field in *TripplePhoto → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tripple_photo.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image1 field in *TripplePhoto → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tripple_photo.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * Image2 field in *TripplePhoto → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tripple_photo.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * Imag3 field in *TripplePhoto → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tripple_photo.default.primary.imag3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imag3: prismic.ImageField<never>;
}

/**
 * Default variation for TripplePhoto Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripplePhotoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TripplePhotoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TripplePhoto*
 */
type TripplePhotoSliceVariation = TripplePhotoSliceDefault;

/**
 * TripplePhoto Shared Slice
 *
 * - **API ID**: `tripple_photo`
 * - **Description**: TripplePhoto
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripplePhotoSlice = prismic.SharedSlice<
  "tripple_photo",
  TripplePhotoSliceVariation
>;

/**
 * Default variation for YouMayAlsoLike Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type YouMayAlsoLikeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *YouMayAlsoLike*
 */
type YouMayAlsoLikeSliceVariation = YouMayAlsoLikeSliceDefault;

/**
 * YouMayAlsoLike Shared Slice
 *
 * - **API ID**: `you_may_also_like`
 * - **Description**: YouMayAlsoLike
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type YouMayAlsoLikeSlice = prismic.SharedSlice<
  "you_may_also_like",
  YouMayAlsoLikeSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AuthorDocument,
      AuthorDocumentData,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      BlogwithphotosDocument,
      BlogwithphotosDocumentData,
      BlogwithphotosDocumentDataTableItem,
      BlogwithphotosDocumentDataSlicesSlice,
      PawBlogDocument,
      PawBlogDocumentData,
      PawBlogDocumentDataSlicesSlice,
      PawBlogTestDocument,
      PawBlogTestDocumentData,
      PawBlogTestDocumentDataSlicesSlice,
      AllDocumentTypes,
      AuthorBoxSlice,
      AuthorBoxSliceDefaultPrimary,
      AuthorBoxSliceVariation,
      AuthorBoxSliceDefault,
      BulletsSlice,
      BulletsSliceDefaultPrimaryBulletsItem,
      BulletsSliceDefaultPrimary,
      BulletsSliceVariation,
      BulletsSliceDefault,
      CalloutSlice,
      CalloutSliceDefaultPrimary,
      CalloutSliceVariation,
      CalloutSliceDefault,
      ContentCenteredSlice,
      ContentCenteredSliceDefaultPrimaryBulletsItem,
      ContentCenteredSliceDefaultPrimary,
      ContentCenteredSliceVariation,
      ContentCenteredSliceDefault,
      ContentWithTestimonialsAndStatsSlice,
      ContentWithTestimonialsAndStatsSliceDefaultPrimary,
      ContentWithTestimonialsAndStatsSliceVariation,
      ContentWithTestimonialsAndStatsSliceDefault,
      CtaInfoSlice,
      CtaInfoSliceDefaultPrimary,
      CtaInfoSliceVariation,
      CtaInfoSliceDefault,
      FaqsSlice,
      FaqsSliceDefaultPrimaryQuestionsAndAnswersItem,
      FaqsSliceDefaultPrimary,
      FaqsSliceVariation,
      FaqsSliceDefault,
      H1WithSubHeadingSlice,
      H1WithSubHeadingSliceDefaultPrimary,
      H1WithSubHeadingSliceVariation,
      H1WithSubHeadingSliceDefault,
      H1WithSubHeadingSliceH2WithSubheading,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SectionRichTextImageSlice,
      SectionRichTextImageSliceDefaultPrimary,
      SectionRichTextImageSliceVariation,
      SectionRichTextImageSliceDefault,
      SectionWithHeadingSlice,
      SectionWithHeadingSliceDefaultPrimary,
      SectionWithHeadingSliceVariation,
      SectionWithHeadingSliceDefault,
      TableSlice,
      TableSliceDefaultPrimaryRowsItem,
      TableSliceDefaultPrimary,
      TableSliceVariation,
      TableSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
      TldrBoxSlice,
      TldrBoxSliceDefaultPrimary,
      TldrBoxSliceVariation,
      TldrBoxSliceDefault,
      TripplePhotoSlice,
      TripplePhotoSliceDefaultPrimary,
      TripplePhotoSliceVariation,
      TripplePhotoSliceDefault,
      YouMayAlsoLikeSlice,
      YouMayAlsoLikeSliceVariation,
      YouMayAlsoLikeSliceDefault,
    };
  }
}
