import "@/styles/globals.css";
import { Analytics } from "@vercel/analytics/react";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Footer } from "./Footer";
import { Header } from "./Header";
import { Toaster } from "@/app/_components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
import { SpeedInsights } from "@vercel/speed-insights/next";
import { PHProvider } from "./_components/PostHogProvider";

import dynamic from "next/dynamic";
import { PrismicPreview } from "@prismicio/next";

const PostHogPageView = dynamic(() => import("./PostHogPageView"), {
  ssr: false,
});

// export const metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Swipestats | Visualize your Tinder data</title>
        <meta name="title" content="Swipestats | Visualize your Tinder data" />
        <meta
          name="description"
          content="Upload your dating data anonymously and compare it to demographics from around the world!"
        />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://swipestats.io/" />
        <meta
          property="og:title"
          content="Swipestats | Visualize your Tinder data"
        />
        <meta
          property="og:description"
          content="Upload your dating data anonymously and compare it to demographics from around the world!"
        />
        <meta property="og:image" content="/ss2.png" />

        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://swipestats.io/" />
        <meta
          property="twitter:title"
          content="Swipestats | Visualize your Tinder data"
        />
        <meta
          property="twitter:description"
          content="Upload your dating data anonymously and compare it to demographics from around the world!"
        />
        <meta property="twitter:image" content="/ss2.png" />

        <link rel="icon" href="/swipestatsFireLogo.svg" />
      </head>
      <body className={`font-sans ${inter.variable} bg-white`}>
        <TRPCReactProvider>
          <PHProvider>
            <Header />
            <main className="mt-20">{children}</main>
            <Footer />
            <PostHogPageView />
            <PrismicPreview repositoryName={"swipestats"} />
          </PHProvider>
        </TRPCReactProvider>
        <Analytics />
        <SpeedInsights />
        <Toaster />
      </body>
    </html>
  );
}
