// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  alternate_grid_2: dynamic(() => import("./AlternateGrid2")),
  author_box: dynamic(() => import("./AuthorBox")),
  bullets: dynamic(() => import("./Bullets")),
  call_to_action: dynamic(() => import("./CallToAction")),
  callout: dynamic(() => import("./Callout")),
  content_centered: dynamic(() => import("./ContentCentered")),
  content_with_testimonials_and_stats: dynamic(
    () => import("./ContentWithTestimonialsAndStats"),
  ),
  cta_info: dynamic(() => import("./CtaInfo")),
  faqs: dynamic(() => import("./Faq")),
  h1_with_sub_heading: dynamic(() => import("./HeadingWithSubHeading")),
  hero: dynamic(() => import("./Hero")),
  hero_section: dynamic(() => import("./HeroSection")),
  rich_text: dynamic(() => import("./RichText")),
  section_rich_text_image: dynamic(() => import("./SectionRichTextImage")),
  section_with_heading: dynamic(() => import("./SectionWithHeading")),
  table: dynamic(() => import("./Table")),
  testimonial: dynamic(() => import("./Testimonial")),
  tldr_box: dynamic(() => import("./TldrBox")),
  tripple_photo: dynamic(() => import("./TripplePhoto")),
  you_may_also_like: dynamic(() => import("./YouMayAlsoLike")),
};
